# Generated by Django 5.2.3 on 2025-06-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BankName', models.CharField(max_length=100)),
                ('QR', models.ImageField(upload_to='QR_images/')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=128)),
                ('Phone', models.CharField(max_length=20)),
                ('Pan', models.CharField(max_length=10, unique=True)),
                ('Pan_card_Image', models.ImageField(upload_to='pan_cards/')),
                ('Account_No', models.CharField(max_length=50)),
                ('IFSC_code', models.CharField(max_length=20)),
                ('Cancel_cheque_or_bank_statement', models.ImageField(upload_to='bank_documents/')),
            ],
        ),
        migrations.CreateModel(
            name='withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Amount', models.CharField(blank=True, max_length=200, null=True)),
                ('Status', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
