# Generated by Django 5.2.3 on 2025-06-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_deposit_user_withdrawal_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositAccountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BankName', models.CharField(max_length=200)),
                ('HolderName', models.CharField(max_length=200)),
                ('AccountNumber', models.CharField(max_length=50)),
                ('IFSC', models.CharField(max_length=20)),
                ('QRImage', models.ImageField(upload_to='QR_images/')),
            ],
        ),
    ]
